# sequences = {"seq1":"TACTTTATATTTTATTTTTGGAATTTGAGCAGGAATAGTTGGGACATCTTTAAGTCTTTTAATTCGAACAGAATTAGGAACTCCTGGATCTTTAATTGGTGATGATCAAATTTATAATACTATTGTTACAGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTATAATTGGAGGATTTGGTAATTGATTAGTACCCCTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAATTTTATTAATTTCAAGAAGAATCGTAGAAAATGGTGCAGGAACAGGATGAACAGTTTACCCCCCACTTTCATCAAATATTGCTCATAGAGGATCTTCTGTAGATCTAGCTATTTTTTCTTTACATTTAGCTGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTACTACAATCTTAAATATACGAATTAATAATATAACATTTGATCAAATACCTTTATTTGTTTGAGCAGTAGGTATTACAGCTCTTCTTTTATTACTTTCTTTACCAGTTTTAGCAGGAGCAATTACTATACTTCTTACTGATCGAAATTTAAATACTTCTTTTTTTGATCCTGCTGGTGGAGGAGACCCTATTTTATATCAACATTTATTT","seq2":"TACTTTATATTTTATTTTTGGAATTTGAGCAGGAATAGTTGGGACATCTTTAAGTCTTTTAATTCGAACAGAATTAGGAACTCCTGGATCTTTAATTGGTGATGATCAAATTTATAATACTATTGTTACAGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTATAATTGGAGGATTTGGTAATTGATTAGTACCCCTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAATTTTATTAATTTCAAGAAGAATCGTAGAAAATGGTGCAGGAACAGGATGAACAGTTTACCCCCCACTTTCATCAAATATTGCTCATAGAGGATCTTCTGTAGATCTAGCTATTTTTTCTTTACATTTAGCTGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTACTACAATCTTAAATATACGAATTAATAATATAACATTTGATCAAATACCTTTATTTGTTTGAGCAGTAGGTATTACAGCTCTTCTTTTATTACTTTCTTTACCAGTTTTAGCAGGAGCAATTACTATACTTCTTACTGA----------------------------------------------------------------------"}
#Find the number of mismatches between two sequences
# seq1 = """TACTTTATATTTTATTTTTGGAATT---GCAGGAA---TTGGGACATCTT---GTCTTTT
# AATTCGAACAGAAT---GAACTCCTGGGTCTT---TTGG------TCAAATTTA---TAC
# TATTGTTACAGCTCATGCTTTTATTA---TTTTTTTTA---TTATACCAATTA---TTGG
# AGGATTCGGAAAT---T---TACCTC---TAT---GAGCTCC---TA---CTTTCCCCCG
# AA---A---TA---GATTT---CTTTTACCCCCATCAT---TTTTAT---TTTCAAGAAG
# AATCG---AAAATGGTGCAGGAACAGGA---ACAGTTTACCCCCCACTTTCATCAAATAT
# TGCTCA---AGGATCTTCTG---ATC---CTATTTTTTCTTTACATT---CTGGAATTTC
# ATCTATTT---GAGCTAT---TTTTATTACTACAATCT---ATATACGAAT------TAT
# AACATT---TCAAATACCTTTATTTGTT---GCAG---GTATTACAGCTCTTCTTTTATT
# ACTTTCTTTACCAGTTT---CAGGAGCAATTACTATACTTCTTAC---TCGAAATT---A
# TACTTCTTTTTT---TCCTGC-------------------------------------"""
# seq2 = "TACTTTATATTTTATTTTTGGAATTTGAGCAGGAATAGTTGGGACATCTTTAAGTCTTTTAATTCGAACAGAATTAGGAACTCCTGGATCTTTAATTGGTGATGATCAAATTTATAATACTATTGTTACAGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTATAATTGGAGGATTTGGTAATTGATTAGTACCCCTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAATTTTATTAATTTCAAGAAGAATCGTAGAAAATGGTGCAGGAACAGGATGAACAGTTTACCCCCCACTTTCATCAAATATTGCTCATAGAGGATCTTCTGTAGATCTAGCTATTTTTTCTTTACATTTAGCTGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTACTACAATCTTAAATATACGAATTAATAATATAACATTTGATCAAATACCTTTATTTGTTTGAGCAGTAGGTATTACAGCTCTTCTTTTATTACTTTCTTTACCAGTTTTAGCAGGAGCAATTACTATACTTCTTACTGA----------------------------------------------------------------------"
# seq2 = "TACTTTATATTTTATTTTTGGAATTTGAGCAGGAATAGTTGGGACATCTTTAAGTCTTTTAATTCGAACAGAATTAGGAACTCCTGGATCTTTAATTGGTGATGATCAAATTTATAATACTATTGTTACAGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTATAATTGGAGGATTTGGTAATTGATTAGTACCCCTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAATTTTATTAATTTCAAGAAGAATCGTAGAAAATGGTGCAGGAACAGGATGAACAGTTTACCCCCCACTTTCATCAAATATTGCTCATAGAGGATCTTCTGTAGATCTAGCTATTTTTTCTTTACATTTAGCTGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTACTACAATCTTAAATATACGAATTAATAATATAACATTTGATCAAATACCTTTATTTGTTTGAGCAGTAGGTATTACAGCTCTTCTTTTATTACTTTCTTTACCAGTTTTAGCAGGAGCAATTACTATACTTCTTACTGA"

def read_fasta(filename):
    f = open(filename, "r")
    Lines = f.readlines()
    # print(f.read())
    seqs = [""]
    i = -1
    for line in Lines:
        if len(line) < 10:
            continue
        if ">" in line:
            i += 1
            seqs.append("")
            continue
        else:
            line = line.strip('\n')
            seqs[i] += line
    min_len = 999999999
    min_index = 0
    for j in range(0, len(seqs)):            
        if (len(seqs[j]) < min_len and len(seqs[j]) != 0): 
            min_len = len(seqs[j])
            min_index = j
    #     print(j, " ", len(seqs[j]),"\n", seqs[j], "\n")
    # print (len(seqs[min_index]))
    for j in range(0, len(seqs)):
        seqs[j] = seqs[j][0, len(seqs[min_index])] # make len of shortest
        print(j, " ", len(seqs[j]),"\n", seqs[j], "\n")
    return len(seqs[min_index])
    




filename = "files/fancyname.txt"
min_len = read_fasta(filename)






# length_of_shorter_seq = min(len(seq1),len(seq2))

# shared = 0
# different = 0
# for i in range(length_of_shorter_seq):
#     if seq1[i] == seq2[i]:
#         shared += 1
#     else:
#         different +=1

# sequence_identity = shared/length_of_shorter_seq
# print(f"There were {shared} shared nucleotides and {different} different nucleotides among the sequences")
# print(f"Sequence identity: {round(sequence_identity,2)}")       
